export const SYSTEM_CATEGORIES = [
  { name: 'Food & Dining', icon: '🍽️', type: 'expense' as const },
  { name: 'Transport', icon: '🚗', type: 'expense' as const },
  { name: 'Shopping', icon: '🛍️', type: 'expense' as const },
  { name: 'Entertainment', icon: '🎬', type: 'expense' as const },
  { name: 'Health & Medical', icon: '💊', type: 'expense' as const },
  { name: 'Education', icon: '📚', type: 'expense' as const },
  { name: 'Utilities', icon: '💡', type: 'expense' as const },
  { name: 'Housing', icon: '🏠', type: 'expense' as const },
  { name: 'Travel', icon: '✈️', type: 'expense' as const },
  { name: 'Family & Kids', icon: '👨‍👩‍👧', type: 'expense' as const },
  { name: 'Gifts & Donations', icon: '🎁', type: 'expense' as const },
  { name: 'Salary', icon: '💰', type: 'income' as const },
  { name: 'Freelance', icon: '💻', type: 'income' as const },
  { name: 'Rental Income', icon: '🏘️', type: 'income' as const },
  { name: 'Investment Returns', icon: '📈', type: 'income' as const },
  { name: 'Gifts Received', icon: '🎁', type: 'income' as const },
  { name: 'Transfer', icon: '🔄', type: 'both' as const },
  { name: 'Adjustment', icon: '⚖️', type: 'both' as const },
  { name: 'Others', icon: '📦', type: 'both' as const },
]
